#!/usr/bin/env bash

while [ ! "${DHT_PIN}" ]
do
    echo -n "Which pin is the DHT humidity and temperature sensor connected to? "
    read DHT_PIN
done

while [ ! "${IR_SEND_PIN}" ]
do
    echo -n "Which pin is the infra-red LED connected to? "
    read IR_SEND_PIN
done

echo "#define DHT_PIN ${DHT_PIN}
#define IR_SEND_PIN ${IR_SEND_PIN}" > Pins.h

# vim: syntax=sh expandtab tabstop=4 shiftwidth=4 softtabstop=4:
