#!/usr/bin/env bash
#
# vim: syntax=sh expandtab tabstop=4 shiftwidth=4 softtabstop=4:
#

cd `dirname $0`
html-minifier --collapse-whitespace --remove-comments --minify-css true --minify-js true index.html -o index.min.html
./printify | tee ../IndexHtml.h >& /dev/null
