#!/usr/bin/env node
const fs = require("fs");

fs.readFile("index.min.html",{encoding: 'utf8'}, (err, data) => {
    if (err)
        throw err;

    // Load the file contents to a string
    const fileContents = data.toString();

    // Final output
    console.log('static const char* indexHtml = "' + fileContents.replace(/\"/g, '\\"') + '";');
});

// vim: syntax=javascript expandtab tabstop=4 shiftwidth=4 softtabstop=4:
